#----------SlimeBucket 1.0------------
# A Minecraft/Spigot Plugin for 1.13.1
# This Plugin Is Made For MumboCraft & It's Players & Staff. 
# Any misuse, unauthorised selling or re-distribution of this plugin will call for said plugin to be removed
# Plugin written by Jamdoggy
# -----------------------------------------------------------
# 
# This plugin currently has no configuration options