#----------SlimeBucket 1.0------------
# A Minecraft/Spigot Plugin for 1.13.1
# This Plugin Is Made For MumboCraft & It's Players & Staff. 
# Any misuse, unauthorised selling or re-distribution of this plugin will call for said plugin to be removed
# Plugin written by Jamdoggy
# -----------------------------------------------------------
# 
# DebugMessages: Put debug messages in log (false=off, true=on)
DebugMessages: false
# LogMessages: Put standard messages in log when player detects a slime chunk, or catches/releases a slime. (false=off, true=on)
LogMessages: true